name: {{ cookiecutter.project_slug  }}
channels:
    - conda-forge
    - defaults
dependencies:
{% if cookiecutter.language in ['Python', 'Both']
%}    - pip
    - black
    - jupyterlab{% endif %}
{% if cookiecutter.language in ['R', 'Both']
%}    - r
    - r-styler{% endif %}
{% if cookiecutter.manuscript_format == 'R Markdown' or cookiecutter.language == 'R'
%}    - r-rmarkdown{% endif %}
{% if cookiecutter.add_dvc == 'y'
%}    - dvc{% endif %}
