name: {{ cookiecutter.project_slug  }}
channels:
    - conda-forge
    - defaults
dependencies:
    - pip
    - black
{% if cookiecutter.add_dvc == 'y'
%}    - dvc{% endif %}
{% if cookiecutter.add_git_pre_commit_hook_black == 'y'
%}    - pre-commit{% endif %}
{% if cookiecutter.manuscript_format == 'R Markdown'
%}    - r-rmarkdown{% endif %}
